[colors.primary]
background = '#1a1110'
foreground = '#f1dfdb'

[colors.selection]
text = '#f1dfdb'
background = '#733429'

[colors.cursor]
text = '#1a1110'
cursor = '#ffb4a7'

[colors.normal]
black   = '#1a1110'
red     = '#ff7572'
green   = '#99ff7f'
yellow  = '#ffe472'
blue    = '#f29c8d'
magenta = '#76362b'
cyan    = '#ffb4a7'
white   = '#fff1ef'

[colors.bright]
black   = '#a59b99'
red     = '#ffa19f'
green   = '#b7ffa5'
yellow  = '#ffeea5'
blue    = '#ffbfb4'
magenta = '#ffcac1'
cyan    = '#ffddd7'
white   = '#fff9f8'
