[colors.primary]
background = '#1a110f'
foreground = '#f1dfda'

[colors.selection]
text = '#f1dfda'
background = '#723523'

[colors.cursor]
text = '#1a110f'
cursor = '#ffb5a0'

[colors.normal]
black   = '#1a110f'
red     = '#ff7672'
green   = '#98ff7f'
yellow  = '#ffe572'
blue    = '#f29d85'
magenta = '#763725'
cyan    = '#ffb5a0'
white   = '#fff3ef'

[colors.bright]
black   = '#a59c99'
red     = '#ffa19f'
green   = '#b7ffa5'
yellow  = '#ffeea5'
blue    = '#ffc0ae'
magenta = '#ffcbbc'
cyan    = '#ffddd4'
white   = '#fffaf8'
