[colors.primary]
background = '#131318'
foreground = '#e4e1e9'

[colors.selection]
text = '#e4e1e9'
background = '#404178'

[colors.cursor]
text = '#131318'
cursor = '#c1c1ff'

[colors.normal]
black   = '#131318'
red     = '#ff7294'
green   = '#7fff96'
yellow  = '#ffd872'
blue    = '#ababf2'
magenta = '#414176'
cyan    = '#c1c1ff'
white   = '#efefff'

[colors.bright]
black   = '#9999a5'
red     = '#ff9fb6'
green   = '#a5ffb5'
yellow  = '#ffe6a5'
blue    = '#cacaff'
magenta = '#d3d3ff'
cyan    = '#e3e3ff'
white   = '#f8f8ff'
