# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf


################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,1
# monitor=HDMI-A-5,preferred,auto,1.33333
# monitor=HDMI-A-5,preferred,auto,0.8


# Force software cursor
# If a duplicate cursor seems to be stuck
# cursor:no_hardware_cursors = true


###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
# $menu = wofi --show drun
# to toggle wofi
$menu = ~/.config/hypr/scripts/wofi-toggle.sh
# in order to run it a bit faster as told in the documentation
# note that in order for this to work, `walker --gapplication-service` must
# be running, hence added that to exec-once
# $menu = nc -U /run/user/1000/walker/walker.sock
# $menu = walker


#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = waybar & swaync & hypridle & hyprpaper & elephant
# this makes walker run only as a gapplication-service
# & walker --gapplication-service


#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

source = ~/.config/hypr/permissions.conf
source = ~/.config/hypr/initial_after_permissions.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windows_and_workspaces.conf
