cursor #f1dfdb
cursor_text_color #d8c2be

foreground            #f1dfdb
background            #1a1110
selection_foreground  #442a25
selection_background  #e7bdb5
url_color             #ffb4a7

color0   #1a1110
color1   #ff7572
color2   #99ff7f
color3   #ffe472
color4   #f29c8d
color5   #76362b
color6   #ffb4a7
color7   #fff1ef
color8   #a59b99
color9   #ffa19f
color10  #b7ffa5
color11  #ffeea5
color12  #ffbfb4
color13  #ffcac1
color14  #ffddd7
color15  #fff9f8
