cursor #f1dfda
cursor_text_color #d8c2bc

foreground            #f1dfda
background            #1a110f
selection_foreground  #442a22
selection_background  #e7bdb2
url_color             #ffb59f

color0   #1a110f
color1   #e14983
color2   #9ad66e
color3   #dbaa7b
color4   #c1694f
color5   #bf9285
color6   #ffb59f
color7   #abb2bf
color8   #5c6370
color9   #e05f93
color10  #ace086
color11  #e8bf97
color12  #ffc1aa
color13  #ba5e57
color14  #9e6f55
color15  #ffffff
