cursor #e5e1e9
cursor_text_color #c8c5d0

foreground            #e5e1e9
background            #131318
selection_foreground  #2f2e42
selection_background  #c7c4dd
url_color             #c3c0ff
color0   #131318
color1   #e35044
color2   #6ed672
color3   #dbd67b
color4   #7f72e9
color5   #9b99bf
color6   #c3c0ff
color7   #abb2bf
color8   #5c6370
color9   #e0665f
color10   #86e089
color11   #e8e497
color12   #d1ceff
color13   #6c71c8
color14   #7e6eba
color15   #ffffff
